version: '3'
services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.1
        container_name: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        networks:
            - app-network
        depends_on:
            - db
            - webserver
        command: >
            bash -c "php artisan key:generate && php artisan migrate:refresh --seed && php artisan passport:install && php-fpm"

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: always
        tty: true
        ports:
            - "5000:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

    # MySQL Service
    db:
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: gradus_db
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

    web:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        volumes:
        - ./frontend/src:/usr/src/app/src
        - ./frontend/public:/usr/src/app/public
        container_name: web
# Docker Networks
networks:
    app-network:
        driver: bridge
